# Generated by Django 3.2.5 on 2021-07-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(help_text='The title of the book', max_length=50, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, help_text='The name of the author of the book', max_length=50, null=True)),
                ('date_of_publication', models.DateField(blank=True, help_text='The date of publication of the book', null=True)),
                ('number_of_pages', models.IntegerField(help_text='The number of pages in the book', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('region_id', models.IntegerField(help_text='The region id of the school', max_length=3)),
                ('school', models.CharField(help_text='The name of the school', max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='The email id associated with the school', max_length=30)),
                ('principal', models.CharField(help_text='The name of the principal of the school', max_length=40)),
                ('phone', models.CharField(help_text='The phone number associated with the school', max_length=8)),
                ('address2', models.CharField(help_text='The 2nd address line of the school', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='The first name of the student', max_length=20)),
                ('last_name', models.CharField(blank=True, help_text='The last name of the student', max_length=20, null=True)),
                ('email', models.EmailField(help_text='The email id of the student', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], help_text='The gender of the student', max_length=1, null=True)),
                ('books', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.book')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.school')),
            ],
        ),
    ]
