# Generated by Django 3.2.5 on 2021-07-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(help_text='The number of pages in the book'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region_id',
            field=models.IntegerField(help_text='The region id of the school'),
        ),
    ]
